n_grid: 128
density_threshold: 20.0
search_threshold: 0.2
search_exclude_direction: -1
ray_cast_direction: 4
max_particles_num: 500000
max_particles_per_cell: 4
boundary: [0.2, 1.8, 0.2, 1.8, 0.2, 1.8]
smooth: true
visualize: false
